version: "3"
services:
    web:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - testVolume:/src/data
        environment:
            DATA_PATH: /src/data/MenuSites.json

volumes:
    testVolume:
